### ISSUE TITLE
Why not use the exiv2?

### ISSUE THREAD

**Issue by fabianski7** [Merrit/kde-dolphin-remove-metadata#1]
[exiv2](https://www.exiv2.org/) is a necessary dependency of kde plasma to obtain the file metadata and could be used instead of exiftool

**Comment by Merrit** [comment]
I didn't realize this was a thing, looks very promising. Always great to have a tool without dependencies - will look into it further. Thanks!

**Comment by Merrit** [comment]
Resolved with #3, where we discovered exiv2 is the library KDE uses but for user-facing actions still requires an external tool download. Thanks for the issue! :)
